name: Node CI

on: [push]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        node-version: [8.x, 10.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Remove Package Lock
      if: matrix.os != 'windows-latest'
      run: 
        rm -rf $GITHUB_WORKSPACE/package-lock.json
    - name: Install Dependencies
      run: npm install
    - name: Build Code
      run: |
        npm run build
      env:
        CI: true
