name: Environment Variables

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - run: echo $ENCRYPTION_KEY
    - name: Set up environment variables 
      env:
        ENCRYPTION_KEY: ${{ secrets.ENCRYPT_KEY }}
